# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8 
    commands:
      # This is a test again
      - echo install serverless
      - npm install -g mocha
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
      - npm install --save-dev jest
      # git remote add origin https://github.com/susmithagankidi/testlambda.git
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - mkdir mygit
      - cd mygit
      - git init
      - ls -la .git/
      - ls -la
      - git pull https://github.com/susmithagankidi/testlambda.git
      - git status
      - git whatchanged -n 1 >file1.txt
      - cat file1.txt
      -  sh test.sh
      - rm -rf node_modules
  post_build:
    commands:
      - echo Build completed on `date`
      - sls config credentials --provider aws --key $KEY --secret $SECRET
      - sls deploy --region us-east-1 --verbose
      - echo Build completed

artifacts:
  files:
    - '**/*'
    - serverless.yml
