# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8 
    commands:
      - echo install serverless
      - npm install -g mocha
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
      # git remote add origin https://github.com/susmithagankidi/testlambda.git
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -la
      - git log
      - cd dev_isr_fetch_mqa_active_alarms_per_site
      - npm test
      - cd ../lz_isr_fetch_user_data_function04
      - npm test
      - rm -rf node_modules
  post_build:
    commands:
      - echo Build completed on `date`
      - sls config credentials --provider aws --key $KEY --secret $SECRET
      - sls deploy --region us-east-1 --verbose
      - echo Build completed

artifacts:
  files:
    - '**/*'
    - serverless.yml
